### ISSUE TITLE
Joblib throws error if even one of the task times out

### ISSUE THREAD

**Issue by pranavbahl2308** [joblib/joblib#522] opened 2017-05-02 22:17 UTC
When I specify the timeout parameter in Parallel function of joblib the complete process fails even if one of the task times out. Following is code:
`
results = Parallel(n_jobs=-2,timeout=5,
                       verbose=100)(delayed(<function_name>)(param)
                         for param in params])
`
So if any of the call times out the whole parallel loop fails. Is there a way to handle timeout error on per task basis.

**Comment by lesteve** [comment] 2017-05-03 07:23
This is the expected behaviour. It looks like you would be interested by #366. Anything you can do to help get it merged would be very appreciated.

Note that I gave a work-around in https://github.com/joblib/joblib/pull/366#issuecomment-267603530 where it is up to the user to implement the timeout functionality inside the function passed into Parallel.

I am going to close this. Please shout if you strongly disagree.

**Closed by lesteve** 2017-05-03 07:23 UTC

**Comment by pranavbahl2308** [comment] 2017-05-03 15:40
The solution you pointed to is perfect. But I am using rpy2 to run R algorithm which is acting weirdly. The r process doesn't timeout until it finishes it's execution no matter if a put a timeout on python function which contains the rpy2 code. The only option which seems to rightly call the timeout in that case is by using "timeout" parameter in Parallel function but then again there is no way to handle the exception on per task level.
