### ISSUE TITLE
module 'os' has no attribute 'statvfs'

### ISSUE THREAD

**Issue by tianxia3** [joblib/joblib#902] opened 2019-06-29 04:54 UTC
Crashed on Windows: joblib\_memmapping_reducer.py.
Looks like os.statvfs is not available on Windows. Is there a fix for this?

**Comment by pierreglaser** [comment] 2019-07-15 13:21
Hello, we cannot reproduce this on our windows test. Can you provide a minimal reproducing example?

**Comment by ogrisel** [comment] 2019-12-06 14:44
Closing because we cannot reproduce it. Please feel free to reopen with more detailed information on your environment: Python version, Windows version, how did you install Python (windows appstore vs anaconda vs python.org vs something else).

**Comment by sharpe5** [comment] 2022-08-09 11:13
Got this as well, I was running python under Wine on Ubuntu 18.04 LTS. I'm assuming the OP was doing the same. joblib is latest as of 2022-08-09. 

Full trace:

```
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 968, in __call__
    n_jobs = self._initialize_backend()
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 735, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\_memmapping_reducer.py", line 557, in register_new_context
    new_folder_path, _ = _get_temp_dir(
  File "C:\users\root\Local Settings\Application Data\Programs\Python\Python39\lib\site-packages\joblib\_memmapping_reducer.py", line 204, in _get_temp_dir
    shm_stats = os.statvfs(SYSTEM_SHARED_MEM_FS)
AttributeError: module 'os' has no attribute 'statvfs'
```

**Comment by rth** [comment] 2022-10-27 09:50
Can someone please reopen? It is a valid issue. I'm hitting this lately for all recent versions on Joblib on Windows with GitBash with Python installed via miniforge.

The main issue is that [`os.statvfs`](https://docs.python.org/3/library/os.html#os.statvfs) is only available on Unix, while environments like [GitBash](https://gitforwindows.org/) provide a Unix like environment but maybe without all the system calls. Or Python on Windows was compiled without [HAVE_FSTATVFS](https://github.com/python/cpython/blob/a371a7e03e43e08cae70235a71904989c0f57a5e/pyconfig.h.in#L408) not sure.  I didn't happen before, so maybe some build flags changed in conda-forge.


Whatever the reason the code [here](https://github.com/joblib/joblib/blob/978bd903939222d43bbf7865338ef7329210bb21/joblib/_memmapping_reducer.py#L208) should not assume os.statvfs always exists. (BTW, I don't understand how this code can work on Windows in general where `os.statvfs` should not be defined, unless the stdlib docs are wrong).


Also, in my GitBash  runtime on Windows, I do have a `/dev/shm` so falling back to tempfile if os.statvfs  doesn't exist is also not ideal. I don't know if something else could be used as a replacement for os.statvfs.

**Closed** 2022-11-25 00:26 UTC
Labels: windows

**Comment by knighthat** [comment] 2024-02-29 22:17
Seems like this problem reappears on Python 3.12.2

I'm using Windows 10 on QEMU:
``` python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.statvfs(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'statvfs'
```

Same problem on wine:
```python
Z:\home\knighthat>python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on w
in32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.statvfs(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'statvfs'
>>>
```
