### ISSUE TITLE
Nested parallel warnings test failing from time to time in python 3

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#413] opened 2016-10-12 15:56 UTC
This happens only with Travis CI. See [this build](https://travis-ci.org/joblib/joblib/builds/167094907) for example (python 3.3). I also had failing builds with python 3.4 when working on #400 (but they are gone since I manually restarted the failing builds).

**Comment by aabadie** [comment] 2016-10-12 16:00
The failing build pointed in the issue has now gone, since I also restarted it....

**Comment by lesteve** [comment] 2016-10-12 22:18
Do you remember what the error looked like? I have one in my notes that I saw once recently but never before.

**Comment by aabadie** [comment] 2016-10-13 06:16
I don't fully remember the error. But it was something related to the warning message `UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1` being/or not being raised.

Problably similar to this failing build: https://travis-ci.org/joblib/joblib/jobs/165246296

**Comment by lesteve** [comment] 2016-10-21 14:07
At the time I put this test together, I was hoping to get exactly the number of warnings equal to n_jobs in the test, I tried a varied number of stderr flushing strategy and I never could get the test to pass 100% of the time. I finally changed the test to check for one warning only. It's probably the same root cause here.

I am closing this one, feel free to reopen if it does appear again.

**Comment by aabadie** [comment] 2016-11-03 08:18
Looks like #422 encountered the issue again. Here is the full traceback:
```
======================================================================

ERROR: joblib.test.test_parallel.test_nested_parallel_warnings

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/build/joblib/joblib/joblib/test/test_parallel.py", line 837, in test_nested_parallel_warnings

    stderr_regex=regex)

  File "/home/travis/build/joblib/joblib/joblib/testing.py", line 125, in check_subprocess_call

    stderr_regex, stderr))

ValueError: Unexpected stderr: 'Multiprocessing-backed parallel loops cannot be nested' does not match:

''
```

**Comment by lesteve** [comment] 2016-11-03 08:30
I guess we need to try to reproduce it. I am guessing this could be fixed by flusing stderr in strategic places in the test.

**Comment by karandesai-96** [comment] 2016-12-04 05:22
I have added a temporary skip marker and a _TODO_ about this issue in a commit of #433:

```python
# TODO: Fix https://github.com/joblib/joblib/issues/413 and unskip this test
@with_multiprocessing
@skipif(True, 'Uncertain CI failure (Issue #413)')
def test_nested_parallel_warnings():
    # test body
    pass
```

Since the fix of this issue is unrelated to the corresponding PR submitted by me, I have skipped this test to let the CI pass.

The skip marker must be removed by anyone in their PR which would resolve tis issue. Thanks.

**Comment by lesteve** [comment] 2016-12-14 10:32
@karandesai-96 could you try to use `capsys` for this rather than check_subprocess_call. From what I remembered I used check_subprocess_call because there was no way to use warnings.catch_warnings since the warnings happens in a subprocess.

**Comment by karandesai-96** [comment] 2016-12-14 10:54
@lesteve Sure, I'll let you know further on this thread.

**Comment by karandesai-96** [comment] 2016-12-14 17:56
So my test body is:
```python
@with_multiprocessing
def test_nested_parallel_warnings():
    def func():
        return 42

    def parallel_func():
        res = Parallel(n_jobs=1)(delayed(func)() for _ in range(3))
        return res

    Parallel(n_jobs=2)(delayed(parallel_func)() for _ in range(5))
    # rest as it is
```

This runs perfectly fine when executed line y line in shell, or as current `check_subporocess_call` technique. But running this test through `py.test` throws an error at last line:
```
# Python 3.5.2
AttributeError: Can't pickle local object 'test_nested_parallel_warnings.<locals>.func'

# Python 2.7.12
TypeError: can't pickle function objects
```

I saw @GaelVaroquaux 's mail in this archive:
http://librelist.com/browser//joblib/2014/3/7/re-joblib-joblib-can-t-pickle-function-object/

Can you shed some light on this issue ?

**Comment by lesteve** [comment] 2016-12-14 22:13
Move the func and parallel_func outside of the test_nested_parallel_warnings:

```py
from joblib import Parallel, delayed


def func():
    return 42


def parallel_func():
    res = Parallel(n_jobs=1)(delayed(func)() for _ in range(3))
    return res


def test_nested_parallel_warnings():

    Parallel(n_jobs=2)(delayed(parallel_func)() for _ in range(5))
    # rest as it is
```

**Comment by karandesai-96** [comment] 2016-12-15 03:26
```python
from joblib import Parallel, delayed

def func():
    return 42

def parallel_func():
    res = Parallel(n_jobs=X)(delayed(func)() for _ in range(3))
    return res

def test_nested_parallel_warnings():
    Parallel(n_jobs=Y)(delayed(parallel_func)() for _ in range(5))
```

There were two cases originally. I did some testing and following remains consistent for me:
X=1, Y=1 : No warning (original case - passed)
X=1, Y>1 : No warning (original case - failed)
X>1, Y=1 : No warning 
X>1, Y>1 : Warning with expected regex.

I doubt whether this failure has anything to do with `check_subprocess_call`.

**Comment by karandesai-96** [comment] 2016-12-15 05:17
@lesteve `capsys` didn't work because the warnings were raises in child processes. Neither did `pytest.warns` as it internally uses `warnings.check_warnings`... But there's a fixture similar to `capsys`, named `capfd`. Please have a look at the PR, I have put a doc reference in description. It should fix this issue.

**Comment by karandesai-96** [comment] 2016-12-15 08:47
Fit to be closed. :grin:

**Comment by lesteve** [comment] 2016-12-15 08:57
Thanks for tracking this! Something very nifty is to put "Fix #issueNumber" into the PR description this way the issue gets closed automatically when the PR is merged.

**Comment by karandesai-96** [comment] 2016-12-15 08:59
Oh yes, I wrote "Fixes Issue #number " instead of "Fixes #number ", my bad!

**Closed** 2016-12-15 08:59 UTC

**Comment by lesteve** [comment] 2016-12-15 09:03
> Oh yes, I wrote "Fixes Issue #number " instead of "Fixes #number ", my bad!
Ah that's why, makes sense.

> This runs perfectly fine when executed line y line in shell, or as current check_subporocess_call technique. But running this test through py.test throws an error at last line:

Oh yeah and I did not go into details about this but basically the reason it was "working" line by line in shell is because you were not calling the `test_nested_parallel_warnings` if you tried `test_nested_parallel_warnings()` in your shell you would have got a similar error as the pytest one. 

Another way of saying the same thing, you can copy and paste this in a shell:

```py
def function_with_garbage():
    1/0
```

this is going to "work". This is only going to raise an exception when you call the function.

**Comment by karandesai-96** [comment] 2016-12-15 09:06
@lesteve thanks for the explanation, it is clear to me now! :+1:
