### ISSUE TITLE
caching methods --> _pickle.PicklingError

### ISSUE THREAD

**Issue by chanansh** [joblib/joblib#452] opened 2016-12-12 13:08 UTC
My code is as follows:

    def query(self, query):
        """
        :param query: query string
        :return:
        """
        result = pd.read_sql(sql=query, con=self.engine) # pd = pandas
        return result

and in the class init I do:

        self.query = memory.cache(self.query)

When I run I get the following run time error:
> _pickle.PicklingError: ("Can't pickle <class 'module'>: it's not found as builtins.module", 'PicklingError while hashing {\'query\': \'select company_name, COUNT(*) AS count from dwh.call GROUP BY company_name ORDER BY count DESC\', \'self\': <DataScience.utils.db.GongDbConnector object at 0x000001D39F1CEF28>}: PicklingError("Can\'t pickle <class \'module\'>: it\'s not found as builtins.module",)')

my method for caching follows the [guidlines ](https://pythonhosted.org/joblib/memory.html) (see "caching methods") so I don't follow why it does not work.

**Comment by GaelVaroquaux** [comment] 2016-12-12 15:09
SQL queries don't pickle. You cannot cache them.

**Comment by chanansh** [comment] 2016-12-12 16:26
It's a dataframe. It has pickle ability

**Comment by GaelVaroquaux** [comment] 2016-12-12 17:40
> It's a dataframe. It has pickle ability

I think that it is the input argument that it posing problem, not the
output one. It must pickle also for the hashing to work.

**Comment by chanansh** [comment] 2016-12-12 17:41
Any suggestions for a work around to cache query results?

**Comment by GaelVaroquaux** [comment] 2016-12-12 17:43
> Any suggestions for a work around to cache query results?

Give another representation of the query. I don't know which other, I
don't work with SQL queries.

**Comment by lesteve** [comment] 2016-12-13 13:20
I have a small example that is working for me using sqlite, so I don't think anything is wrong with pandas DataFrame picklability or joblib caching. Can you pickle your `DataScience.utils.db.GongDbConnector` object, I would guess that is where the problem is.

Here is the snippet:

```py
import sqlite3

import pandas as pd

import joblib

query = 'select * from projects;'


def create_table():
    create_table_query = """
    CREATE TABLE
    IF NOT EXISTS projects (
     id integer PRIMARY KEY,
     name text NOT NULL
    );
    """
    template_insert_query = "INSERT INTO projects(id,name) VALUES(?,?)"
    con = sqlite3.connect('data.db')
    cursor = con.cursor()
    cursor.execute(create_table_query)

    if not len(execute_query_func(query)):
        for i, t in [(1, 'asd'), (2, 'qwer'), (3, 'zxcv')]:
            cursor.execute(template_insert_query, (i, t))

    con.commit()

mem = joblib.Memory(cachedir='/tmp/joblib')


def execute_query_func(query):
    con = sqlite3.connect('data.db')
    return pd.read_sql(query, con=con)

create_table()

df = mem.cache(execute_query_func)(query)
print(df)


class MyClass(object):
    def __init__(self):
        self.con = sqlite3.connect('data.db')
        self.execute_query_method = mem.cache(self.execute_query_method)

    def execute_query_method(self, query):
        return pd.read_sql(query, con=self.con)


instance = MyClass()
print(instance.execute_query_method(query))
```

For the record, we updated the doc recently to make it more clear than cache class methods is not recommended and that the way to go is to use pure functions.

**Comment by lesteve** [comment] 2016-12-15 09:06
> I think that it is the input argument that it posing problem, not the output one. It must pickle also for the hashing to work.

The problem is the input argument indeed but since `query`  is a string, the problem is not in the query but in the `self`, that is why I asked whether the `DataScience.utils.db.GongDbConnector` was picklable earlier? @chanansh have you tried this?

**Comment by GaelVaroquaux** [comment] 2016-12-15 11:31
> The problem is the input argument indeed but since query is a string, the
> problem is not in the query but in the self,

So we are back to the fact that caching methods is a bad idea, and
ideally functions should be cached.

**Comment by lesteve** [comment] 2016-12-15 14:31
> So we are back to the fact that caching methods is a bad idea, and ideally functions should be cached.

+1 to that.

**Comment by lesteve** [comment] 2016-12-19 13:32
@chanansh I am going to close this one, please shout if you think something is wrong on the joblib side.

**Closed by lesteve** 2016-12-19 13:32 UTC
