### ISSUE TITLE
Pass **kwargs to Pool

### ISSUE THREAD

**Issue by demodw** [joblib/joblib#359] opened 2016-06-10 09:40 UTC
Hi,

I am running into a problem when executing a lot of tasks in Parallel. The memory consumption is growing and growing. Some googling indicated that this could be solved by passing the maxtasksperchild=1000 to the mp.Pool constructor (http://stackoverflow.com/questions/21485319/high-memory-usage-using-python-multiprocessing), which will cause the pool to refresh its child processes.

I could not find any way of passing down this argument using joblib. Or is there maybe another solution?

Cheers,
David

**Comment by lesteve** [comment] 2016-06-10 12:10
First thing to try: modify your joblib copy with the proposed change in the mp.Pool to see whether it changes anything to the memory consumption.

**Comment by demodw** [comment] 2016-06-13 10:59
How would one go about implementing this? Reading into the code, joblib implements its own Pool class.

**Comment by lesteve** [comment] 2016-06-13 11:40
Arguments are passed to base classes through things like: `super(MemmapingPool, self).__init__(...)`:

I haven't tested it but it looks like for joblib master you would need to replace in this line:
https://github.com/joblib/joblib/blob/a96878e2c084ca1347aabbab21048fa08de5d74a/joblib/pool.py#L420

```py
super(PicklingPool, self).__init__(**poolargs)
```
by
```py
super(PicklingPool, self).__init__(maxtasksperchild=some_value_goes_here, **poolargs)
```

**Comment by lesteve** [comment] 2016-06-13 11:41
Just for sake of completeness, this is not a long-term solution, this is just a quick and dirty test to see whether that fixes your problem with memory usage.

**Comment by demodw** [comment] 2016-06-13 11:50
OK. I will give it a try and report back in a few days.

**Comment by kernc** [comment] 2016-07-15 12:06
@demodw Any news?

**Comment by ogrisel** [comment] 2016-07-17 18:29
Note that joblib 0.10.0 is out and has a new pluggable backend infrastructure which is quite different from the code base of 0.9.4. The multiprocessing Pool system code is still the same but the way it's called into from the joblib.Parallel class has changed a bit.

**Comment by demodw** [comment] 2016-07-18 11:17
@kernc: sorry for the lack of reply, been on vacation. I found out the issue is most likely related to Fork, and even passing maxtasksperchild did not fix this.

Cheers.

**Comment by GaelVaroquaux** [comment] 2016-07-19 09:21
Should we close this issue, then?

**Comment by lesteve** [comment] 2016-07-21 08:50
Let's close this one, @demodw feel free to reopen if you can come up with a stand-alone example reproducing the problem.

**Closed** 2016-07-21 08:50 UTC

**Comment by you-n-g** [comment] 2021-09-02 04:37
Does  `joblib` provide any approach to pass the `maxtasksperchild` argument when using the multiprocessing backend now?
Thanks
