### ISSUE TITLE
Unexpected reloading of modules when using `loky` backend but not with `multiprocessing` backend

### ISSUE THREAD

**Issue by marcofavorito** [joblib/joblib#1281] opened 2022-03-10 22:20 UTC
If the function used as input for `Parallel` with `backend="loky"` is imported from another module, each worker reloads that module. This does not happen using `backend="multiprocessing"`.

To reproduce:

- use Python 3.8 with `joblib==1.1.0` (the latest version at the time I am writing); I was also able to reproduce the same issue with `joblib` at commit 4dafaff788a3b5402acfed091558b4c511982959.

- save to `external_module.py` the following code:
```python
import time
from datetime import datetime

print(f"[{datetime.now()}] start loading...")
time.sleep(3.0)
print(f"[{datetime.now()}] end loading")


def my_function(i):
    print(f"[{datetime.now()}] start my_function({i})")
    time.sleep(1.0)
    print(f"[{datetime.now()}] end my_function({i})")
    return i
```

- save to `main.py` the following code:
```python
from datetime import datetime

from joblib import Parallel, delayed

from external_module import my_function

if __name__ == '__main__':
    n_jobs = 2
    # backend = "loky"
    backend = "multiprocessing"

    for run in range(3):
        print(f"[{datetime.now()}] run {run}")
        Parallel(n_jobs=n_jobs, backend=backend)(
            delayed(my_function)(i) for i in range(n_jobs)
        )

    print(f"[{datetime.now()}] End")
```

If `backend = "loky"`, you will get something along the lines of:
```
[2022-03-10 23:18:02.352219] start loading...
[2022-03-10 23:18:05.354541] end loading
[2022-03-10 23:18:05.354714] run 0
[2022-03-10 23:18:05.529271] start loading...
[2022-03-10 23:18:05.566802] start loading...
[2022-03-10 23:18:08.532290] end loading
[2022-03-10 23:18:08.532610] start my_function(0)
[2022-03-10 23:18:08.568249] end loading
[2022-03-10 23:18:08.568552] start my_function(1)
[2022-03-10 23:18:09.533684] end my_function(0)
[2022-03-10 23:18:09.569705] end my_function(1)
[2022-03-10 23:18:09.571656] run 1
[2022-03-10 23:18:09.575960] start my_function(0)
[2022-03-10 23:18:09.589243] start my_function(1)
[2022-03-10 23:18:10.576214] end my_function(0)
[2022-03-10 23:18:10.590118] end my_function(1)
[2022-03-10 23:18:10.590678] run 2
[2022-03-10 23:18:10.591937] start my_function(0)
[2022-03-10 23:18:10.596133] start my_function(1)
[2022-03-10 23:18:11.592264] end my_function(0)
[2022-03-10 23:18:11.596266] end my_function(1)
[2022-03-10 23:18:11.597937] End
```

Note the unexpected `start loading...` and `end loading` message pairs (one for each job, `n_jobs=2`), meaning that each worker imports the `external_module.py` again, differently from the behaviour of `"multiprocessing"` backend.

If `backend = "multiprocessing"`, we get:
```
[2022-03-10 23:18:13.198844] start loading...
[2022-03-10 23:18:16.200284] end loading
[2022-03-10 23:18:16.200470] run 0
[2022-03-10 23:18:16.229311] start my_function(0)
[2022-03-10 23:18:16.229500] start my_function(1)
[2022-03-10 23:18:17.230475] end my_function(0)
[2022-03-10 23:18:17.230603] end my_function(1)
[2022-03-10 23:18:17.236012] run 1
[2022-03-10 23:18:17.253205] start my_function(0)
[2022-03-10 23:18:17.253413] start my_function(1)
[2022-03-10 23:18:18.254406] end my_function(0)
[2022-03-10 23:18:18.254591] end my_function(1)
[2022-03-10 23:18:18.260942] run 2
[2022-03-10 23:18:18.291206] start my_function(0)
[2022-03-10 23:18:18.291429] start my_function(1)
[2022-03-10 23:18:19.292297] end my_function(0)
[2022-03-10 23:18:19.292316] end my_function(1)
[2022-03-10 23:18:19.301432] End
```

i.e. no double loading of the module `external_module.py`.

I suspect this is not the intended behaviour of the Loky backend; but maybe this is inevitable, given how Loky backend works.

**Comment by tomMoral** [comment] 2022-03-10 23:01
Hello, thanks for the detailed report.

This is actually the expected behavior for the `loky` backend (and the reason why it exists :) )

With multiprocessing, the workers are created using `fork` without `exec`. This means that the interpreter state in each worker is the same as when the `fork` happened, and thus the module `external_module` is already loaded. However, this causes some issues with other C-libraries such as openMP because while the state is the same, the threads are not duplicated, leading to unintended behavior. So overall, `fork` is a super fast but error prone way to create new processes.

To avoid using `fork` alone, the recommended POSIX way is to use `fork+exec`, which "clears" the interpreter state in each worker. Thus, the module `external_module` will need to be reloaded in each newly spawn worker. While this is longer, this is also safer. And the goal of `loky` is to make the main process reuse as much as possible processes that have been spawned before, to reduce the overhead of importing all the required module if they are imported multiple times.

So yes, it is an extra cost, but as you can see with the multiple run, you only pay that price once per worker at initialization time with the `loky` backend.

**Comment by tomMoral** [comment] 2022-03-14 10:55
Thanks for the feedback. I am closing the issue then.

**Closed by tomMoral** 2022-03-14 10:55 UTC
