### ISSUE TITLE
Error in test test_nested_parallel_warnings

### ISSUE THREAD

**Issue by sergiopasra** [joblib/joblib#691] opened 2018-06-05 09:21 UTC
I'm running the tests of joblib 0.11 and I get the following error
```
capfd = <_pytest.capture.CaptureFixture object at 0x7f4e9e2b3860>

    @with_multiprocessing
    def test_nested_parallel_warnings(capfd):
        if posix is None:
            # This test pass only when fork is the process start method
            raise SkipTest('Not a POSIX platform')
    
        # no warnings if inner_n_jobs=1
        Parallel(n_jobs=2)(delayed(parallel_func)(inner_n_jobs=1)
                           for _ in range(5))
        out, err = capfd.readouterr()
        assert err == ''
    
        #  warnings if inner_n_jobs != 1
        Parallel(n_jobs=2)(delayed(parallel_func)(inner_n_jobs=2)
                           for _ in range(5))
        out, err = capfd.readouterr()
   >       assert 'Multiprocessing-backed parallel loops cannot be nested' in err
  E       AssertionError: assert 'Multiprocessing-backed parallel loops cannot be nested' in ''
```

I'm running this inside a venv with python3, pytest 3.6.0 and joblib 0.11. I obtain the same failure in python 2.7

The file is `joblib/test/test_parallel.py`

**Comment by lesteve** [comment] 2018-06-05 13:14
Weird, we may need more details to reproduce:
* which command do you use to run your tests?
* for further reference can you post the output of:
```py
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import joblib; print("Joblib", joblib.__version__)
```

**Comment by sergiopasra** [comment] 2018-06-05 13:38
I do the following:

$ python3 -m venv test1
$ source test1/bin/activate
(test1) pip install joblib
(test1) pip install pytest
(test1) pytest --pyargs joblib
....
lib64/python3.6/site-packages/joblib/test/test_parallel.py sss.......... [ 80%]
........................................................................ [ 88%]
........................................................................ [ 96%]
..............F.

The test failed above is `test_nested_parallel_warnings`


Platform is:

Linux-4.16.12-200.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
Python 3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

Joblib 0.11

**Comment by lesteve** [comment] 2018-06-05 13:59
Thanks for the details. I can reproduce on joblib 0.11 but it looks like this has been fixed in master. I am going to close this one, do reopen if you manage to reproduce on master.

**Closed by lesteve** 2018-06-05 13:59 UTC
