### ISSUE TITLE
joblib.hash issue - roundtrip through pickle changes hash

### ISSUE THREAD

**Issue by histed** [joblib/joblib#231] opened 2015-08-26 02:24 UTC
The following code shows joblib.hash() can change on a collection containing a numpy float64 constant and a small numpy array, when the object contents seem exactly the same.
```
import cPickle as pickle
import joblib
import numpy as np
d0 = [np.float64(0), np.zeros((2,))]
d1 = pickle.loads(pickle.dumps(d0))
print joblib.hash(d0), d0
print joblib.hash(d1), d1
```
output:
```
3f8b2cfd508e7bc8fb8ef0712eeebeef [0.0, array([ 0.,  0.])]
52e0c4ef5b5f397a6a4c52bcd23d2f84 [0.0, array([ 0.,  0.])]
```
As a workaround, I'm passing all my objects now through pickle/dill:   hash = joblib.hash(dill.dumps(objToHash).  
Thanks for joblib, it's quite useful

**Comment by histed** [comment] 2015-08-26 02:28
Also:
```
np.__version__
Out[478]: '1.9.2'
joblib.__version__
Out[479]: '0.8.2'
sys.version
Out[481]: '2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) \n[GCC 4.2.1 (Apple Inc. build 5577)]'
```

**Comment by ogrisel** [comment] 2015-08-26 10:27
Hum that's bad thanks for the report. We should have test to cover that. @histed Have you tried to investigate to find the root cause? 

Maybe @lesteve you can have a quick look before you leave for your trip in the mountains :) ?

**Comment by lesteve** [comment] 2015-08-27 12:42
I think this is related to https://github.com/joblib/joblib/pull/213 and in particular:

> Also there is a more general problem with hashing which is sensible to pickle memoization, which arguably we should try to fix...

A slightly modified version of your snippet shows that in d0 the dtype is shared between the two arrays but not in d1:

```python
import cPickle as pickle
import joblib
import numpy as np

d0 = [np.float64(0), np.ones(1)]
d1 = pickle.loads(pickle.dumps(d0))

print(joblib.hash(d0), d0)
print(joblib.hash(d1), d1)
print('d0 sharing dtype:', d0[0].dtype is d0[1].dtype)
print('d1 sharing dtype:', d1[0].dtype is d1[1].dtype)
```
with the output:

```
('15e0006c596612fe04be496299948535', [0.0, array([ 1.])])
('76eacf63100d3e59a3812222cc9679a1', [0.0, array([ 1.])])
('d0 sharing dtype:', True)
('d1 sharing dtype:', False)
```

> As a workaround, I'm passing all my objects now through pickle/dill: hash = joblib.hash(dill.dumps(objToHash).

Doesn't seem to do it for me. `joblib.hash(dill.dumps(d0))` does not give the same result as `joblib.hash(dill.dumps(d1))`.

By the way it is not very clear to me why you need to hash pickle/dill dumps, do you mind explaining your use case a little bit?

**Comment by histed** [comment] 2015-08-27 14:55
You're right about the workaround, just pickling to a string does not work.  Roundtripping through pickle does work however:
```
hash = joblib.hash(dill.loads(dill.dumps(objToHash))
```

Re: use case - this has bitten me in two ways:
- I pass an object to an IPython engine to run a simulation, and return results and the input object's hash, to save transmit time.  Then the client looks up the original input object by its hash.  The locally-computed hash and the remotely-computed hash are different because passing the object to the remote involves a roundtrip through pickle.
- Similarly, I have a big set of objects that I'm indexing by hash.  I have code to write the set out to disk and read it back in.  The hash changes between the first time the set is built in memory, and after saving and loading once.

**Comment by lesteve** [comment] 2015-08-28 10:45
Your use case makes total sense.

I still don't quite follow your work-around using dill though. I updated the snippet to do a dill roundtrip:

```python
import cPickle as pickle
import joblib
import dill
import numpy as np

arr_orig = [np.float64(0), np.ones(1)]
arr_pickle_roundtrip = pickle.loads(pickle.dumps(arr_orig))
arr_dill_roundtrip = dill.loads(dill.dumps(arr_orig))

print(joblib.hash(arr_orig), arr_orig)
print(joblib.hash(arr_pickle_roundtrip), arr_pickle_roundtrip)
print(joblib.hash(arr_pickle_roundtrip), arr_dill_roundtrip)

print('arr_orig sharing dtype:', arr_orig[0].dtype is arr_orig[1].dtype)
print('arr_pickle_roundtrip sharing dtype:',
      arr_pickle_roundtrip[0].dtype is arr_pickle_roundtrip[1].dtype)
print('arr_dill_roundtrip sharing dtype:',
      arr_dill_roundtrip[0].dtype is arr_dill_roundtrip[1].dtype)
```

and the output:

```
('15e0006c596612fe04be496299948535', [0.0, array([ 1.])])
('76eacf63100d3e59a3812222cc9679a1', [0.0, array([ 1.])])
('76eacf63100d3e59a3812222cc9679a1', [0.0, array([ 1.])])
('arr_orig sharing dtype:', True)
('arr_pickle_roundtrip sharing dtype:', False)
('arr_dill_roundtrip sharing dtype:', False)
```

so the hash is not stable after a dill roundtrip cycle. Are you saying you always do a pickle roundtrip to compute the hash (in case your objects indexed by hash for example) and never hash the object directly (hence your mention of "slow work-around")?

**Comment by histed** [comment] 2015-08-28 15:42
> Are you saying you always do a pickle roundtrip to compute the hash (in case your objects indexed by hash for example) and never hash the object directly (hence your mention of "slow work-around")?

Yes, that's correct.  Instead of using `joblib.hash(x)`, I use everywhere `joblib.hash(dill.loads(dill.dumps(x)))`.  Then, writing to disk or sending to a parallel job does a second pickle roundtrip --- and the hash seems stable, in my limited testing.

**Comment by GaelVaroquaux** [comment] 2015-09-02 16:07
This is probably related to:
https://github.com/nilearn/nilearn/issues/771

The gist of the problem is that pickling can break the identity of objects. And in particular that with string it messes up with the interning of string that Python does (it was a big surprise to us to discover that if s is a string, "s is s.lower()" is not true.

One example that summarizes the problem is the following (without using joblib for clarity):

1. Changing the identity of object legitimately changes their pickle:
<pre>
In [13]: l = [1, ]
In [14]: pickle.dumps([l, copy.copy(l)])
Out[14]: '(lp0\n(lp1\nI1\naa(lp2\nI1\naa.'
In [15]: pickle.dumps([l, l])
Out[15]: '(lp0\n(lp1\nI1\naag1\na.'
</pre>

2. The identity of strings is not as controlled as it should be:
<pre>
In [16]: s = 'int32'
In [17]: pickle.dumps([s, s])
Out[17]: "(lp0\nS'int32'\np1\nag1\na."
In [18]: pickle.dumps([s, s.lower()])
Out[18]: "(lp0\nS'int32'\np1\naS'int32'\np2\na."
In [19]: s is s.lower()
Out[19]: False
</pre>

3. dtypes objects contain strings, and: when created from the constructors these are created with a call to 'lower()', when created from a pickle they are not. So we have the same objects, that have different identities.

@arthurmensch is onto the problem and will try to fix the problem in joblib by trying to be robust to variation of identity of strings when hashing.

This was really challenging!

**Comment by GaelVaroquaux** [comment] 2015-09-04 15:35
@histed : would you mind checking if PR #239 solves your bug. We think that it does.

**Comment by histed** [comment] 2015-09-07 16:12
@GaelVaroquaux : I tried my testcase with the commit ce69cf6 from @arthurmensch.  The testcase now seems to work.
```
In [6]: d0 = [np.float64(0), np.zeros((2,))]
In [7]: d1 = pickle.loads(pickle.dumps(d0))
In [8]: print joblib.hash(d0), d0
In [9]: print joblib.hash(d1), d1
```

```
2e648f6f7f8b95201ea5c60245cca883 [0.0, array([ 0.,  0.])]
2e648f6f7f8b95201ea5c60245cca883 [0.0, array([ 0.,  0.])]
```

It will take me a week or two to test this in my full code.  I'll let you know if it fails.  Thanks!

**Comment by GaelVaroquaux** [comment] 2015-09-07 17:20
OK, it seems that we are on a good track here! Thanks for reporting.

**Comment by ogrisel** [comment] 2015-09-07 17:54
Closing this as #239 is now in master. Please open a new issue if you find any other problem on your full code.

**Closed by ogrisel** 2015-09-07 17:54 UTC
Labels: Bug
