### ISSUE TITLE
OverflowError: size does not fit in an int

### ISSUE THREAD

**Issue by corydolphin** [joblib/joblib#122] opened 2014-03-04 19:05 UTC
I am having trouble with joblib failing to dump a large (~60GB) numpy matrix.

Using joblib 8.03a, numpy1.8, scipy 13, on ubuntu 13.04, on a 64bit CPU. The error seems to suggest that the size of the data in bytes is larger than an int, which is impossible, as a 64bit int has a max value ~20^63 which is on the order of Yotta bytes. 

Has anyone seen this error? I plan to pull the latest from numpy, joblib and scipy and see if there is something unreleased that fixes this issue.

```python
Failed to save <type 'numpy.ndarray'> to .npy file:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 241, in save
    obj, filename = self._write_array(obj, filename)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 214, in _write_array
    compress=self.compress)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 89, in write_zfile
    file_handle.write(zlib.compress(asbytes(data), compress))
OverflowError: size does not fit in an int

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/data-exploration/lin_regression/get_data.py", line 177, in <module>
    joblib.dump(X, 'scratch/lin_regression_data/%s_X.pkl' % experimentName, compress=3)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 367, in dump
    pickler.dump(value)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 249, in save
    return Pickler.save(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 249, in save
    return Pickler.save(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 249, in save
    return Pickler.save(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 249, in save
    return Pickler.save(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 249, in save
    return Pickler.save(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 486, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by thm1118** [comment] 2015-05-05 07:49
python 3.4 working fine with compress option for large file, may be fixed on 2011。
it is helpful to give this tip in the document

**Comment by mdasadul** [comment] 2016-01-18 13:33
I am having the same issue with python 2.7

**Comment by ogrisel** [comment] 2016-01-18 14:05
> I am having the same issue with python 2.7

Yes this is a bug in the zlib module which is part of the standard library of Python. Please upgrade to Python 3 if you want to use compression on large numpy arrays (3.5 is the current stable release).

**Comment by esc** [comment] 2016-01-18 14:09
@ogrisel how was this fixed in Python 3?

**Comment by ogrisel** [comment] 2016-01-18 14:16
I don't know, I just blindly trusted @thm1118's report. Let me check using the zlib module directly.

**Comment by ogrisel** [comment] 2016-01-18 14:21
Indeed Python 3.5 works while Python 2.7 crashes:

```
$ python3.5 -c "import zlib; zlib.compress(b'a' * (2 ** 31))"
$ python2.7 -c "import zlib; zlib.compress(b'a' * (2 ** 31))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OverflowError: size does not fit in an int
```

Python 3.5's zlib wrapper probably uses `uint` instead of `int` for storing the size of the byte array.

**Comment by mdasadul** [comment] 2016-01-18 14:25
@ogrisel  Thanks for the help

**Comment by ogrisel** [comment] 2016-01-18 14:30
I opened #300 to track the issue of better documenting that limitation of Python 2.

Let me close the current issue.

**Comment by przemyslslaw** [comment] 2016-08-17 12:05
The bug mentioned here still exists in joblib 0.10 and Python 2.7 for non-array objects that are pickled via `Parallel`. It happens because `CustomizablePickler` fails, presumably because of the issue described in #300. The merge #260 does not fix it, because `CustomizablePickler` uses its own `dump`. Is there any workaround?


```
Process PoolWorker-16:
Traceback (most recent call last):
  File "/NS/anaconda/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/NS/anaconda/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/NS/anaconda/anaconda/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/NS/anaconda/anaconda/lib/python2.7/site-packages/joblib/pool.py", line 386, in put
    return send(obj)
  File "/NS/anaconda/anaconda/lib/python2.7/site-packages/joblib/pool.py", line 371, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/NS/anaconda/anaconda/lib/python2.7/pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
error: 'i' format requires -2147483648 <= number <= 214748364
```

**Comment by ogrisel** [comment] 2016-08-17 14:07
Actually there is no easy way to fix this. Let's document it as a limitation of Python 2 as tracked by #300.

**Closed by ogrisel** 2016-08-17 14:07 UTC

**Comment by ogrisel** [comment] 2016-08-17 14:14
@przemyslslaw My previous comment is wrong: the stacktrace you reported is not directly related to the problem reported by @corydolphin which was about zlib compression. In your case zlib is not involved at all. Please feel free to open a new issue with a minimalistic reproduction script.

**Comment by listentojohan** [comment] 2017-03-14 15:28
I am still getting this error for python 3

**Comment by lesteve** [comment] 2017-03-14 15:40
It would be great if you could post a stand-alone snippet reproducing the problem together with the full stacktrace.
