### ISSUE TITLE
invalidate memory.cache after x hours?

### ISSUE THREAD

**Issue by AlJohri** [joblib/joblib#576] opened 2017-12-05 18:49 UTC
hi, is there anyway to invalidate the memory.cache after x hours or days? I'm working with real estate data which takes time to collect so I'd like to cache it but expire the cache after some number of hours

**Comment by lolabis** [comment] 2018-01-03 03:42
Hey, did you find a fix for that?

**Comment by lesteve** [comment] 2018-01-03 13:38
Duplicate of #313, closing.

**Closed by lesteve** 2018-01-03 13:38 UTC
