### ISSUE TITLE
Test passing but error is appended

### ISSUE THREAD

**Issue by jaksmid** [joblib/joblib#328] opened 2016-03-23 15:40 UTC
I am running a test through python setup.py test.
One of the test is using joblib parallell:
```
Parallel(n_jobs=workers, verbose=3)(
    delayed(_dump_f)(source_file) for source_file in source_files)
```
The enrionmnet is virtualenv 2.7.11 on Mac os El Captain.
All test are passing but the test with joblib is appending an error after the tests are run:

```
Ran 53 tests in 0.623s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/smidj/.virtualenvs/ls/lib/python2.7/site-packages/joblib/pool.py", line 552, in <lambda>
    atexit.register(lambda: delete_folder(pool_folder))
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/smidj/.virtualenvs/ls/lib/python2.7/site-packages/joblib/pool.py", line 552, in <lambda>
    atexit.register(lambda: delete_folder(pool_folder))
TypeError: 'NoneType' object is not callable
```

Any ideas? Seems like the test passes and the destruction of joblib pools is somewhat broken in the tests.

Thanks,
Jakub

Edit: maybe related to this: http://stackoverflow.com/questions/33921876/nonetype-not-callable-from-joblib-when-requiring-but-not-using-cv2

**Comment by ogrisel** [comment] 2016-03-24 09:45
Thanks for the report @jaksmid (I edited it to add triple back-ticks to make it more readable). I pushed a tentative workaround in #329. Can you please test it?

I cannot reproduce the original problem on my machine although I tried with Python 2.7 under OSX El Capitan too.

**Comment by jaksmid** [comment] 2016-03-24 13:17
Hi @ogrisel , thanks for quick reply. I have tried your code and the error has changed to "No module named pool". When I corrected the import 
from .pool import delete_folder
to
from joblib.pool import delete_folder
it started to work flawlessly.
Thanks you!

**Comment by ogrisel** [comment] 2016-03-25 10:25
Unfortunately we cannot use absolute imports because we want joblib to be embeddable by other libraries.

I pushed a new commit to my branch in #329. Can you please test if this is fixes the issue for you?

**Comment by ogrisel** [comment] 2016-03-25 16:42
@jaksmid let me know if the new fix works for you. I could not manage to reproduce the original crash on my environment.

**Comment by jaksmid** [comment] 2016-03-29 08:02
Hi, sorry for the delay, I was away from my laptop as there was a public holiday.
Yours seconds commit works like a charm.
Thanks!
Jakub

**Comment by aabadie** [comment] 2016-03-29 08:42
Closing this issue as #329 is merged.

**Closed by aabadie** 2016-03-29 08:42 UTC

**Comment by ogrisel** [comment] 2016-03-29 13:26
Great thanks for the report @jaksmid.
