### ISSUE TITLE
Joblib 'hangs' randomly

### ISSUE THREAD

**Issue by csdenboer** [joblib/joblib#475] opened 2017-01-10 08:35 UTC
I'm trying to use the joblib plugin of dask.distributed. However, I'm facing strange hangs in the Python process from which parallel_backend is called. Everything runs fine for a random number of calls and then after a while the python processes of the worker become idle and the Python process from which joblib is called starts consuming ~150% CPU for an infinite amount of time. If I run exactly the same code, but with :
`    with Parallel(n_jobs=8) as parallel:`
instead of
`    with parallel_backend('dask.distributed', scheduler_host='127.0.0.1:8786'):`
then everything runs fine. I've got everything running on a single server (for testing purposes), so network issues or differences in the environment should not be the problem. The worker is started with nprocs=7 and nthreads=1.

- CentOS (8 cores)
- joblib 0.10.3 py35_0 conda-forge
- dask 0.13.0 py35_0 conda-forge
- distributed 1.15.0 py35_0 conda-forge
- tornado 4.4.1 py35_0

**Comment by ogrisel** [comment] 2017-01-10 08:44
Could you please provide a minimal reproduction script?

**Comment by jjerphan** [comment] 2019-05-22 16:12
Quick follow-up, @csdenboer: do you still have this problem ?

**Comment by ogrisel** [comment] 2019-12-06 13:21
Closing because #875 was closed and we do not know if this is a distinct bug or not. If so please feel free to open a new issue with a minimal reproducer.

**Closed by ogrisel** 2019-12-06 13:21 UTC
Labels: bug, dask backend
