### ISSUE TITLE
caching of methods updating instance variables

### ISSUE THREAD

**Issue by smidm** [joblib/joblib#431] opened 2016-11-29 12:25 UTC
I haven't found an elegant way to cache methods updating instance variables:

```
class Foo(object):

    def __init__(self, args):
        self.data = None

    def compute(self, ...):
        ...  # long computation
        self.data = result
```

One can create a cached private method that is returning computed data, but in this point the caching mechanism is already complicating the code:
```
class Foo(object):

    def __init__(self, args):
        self.data = None
        self.__compute__ = mem.cache(self.__compute__)        

    def compute(self, ...):
        ...
        self.data = self.__compute__(...)
        
    def __compute__(self, ...):
        ...  # long computation
        return result  
```
Proposal: a possible solution could be a specification of altered instance variables in the decorator:
```
self.compute = mem.cache(self.compute, [self.data, ...]) 
```

**Comment by lesteve** [comment] 2016-11-29 15:25
`joblib.Memory.cache` is meant to be used with pure functions. IMHO you are looking for trouble if you are trying to use it for something else. Even caching methods already has caveats.

Your second solution looks fine AFAICT, what's wrong with it?

**Comment by GaelVaroquaux** [comment] 2016-11-29 15:28
> joblib.Memory.cache is meant to be used with pure functions. IMHO you are looking for trouble if you are trying to use it for something else.

Same thoughts here. I am afraid of all kind of nasty bugs due to uncaught
side effects. I personnally try to avoid these things.

**Comment by lesteve** [comment] 2016-11-29 17:15
Just for reference, one of the caveat I was talking about:

```py
from joblib import Memory

mem = Memory('/tmp/cache')


class A(object):
    def __init__(self):
        self.expensive_func = mem.cache(self.expensive_func)

    def expensive_func(self):
        print('calling method')
        return 42

a = A()
a.expensive_func()
a.attr = 'attr'
a.expensive_func()
```

Even if `expensive_func` does not use the `attr` attribute, it gets recomputed. The same thing would happen if by mistake you changed `self` inside `expensive_func`.

I would recommend using something like this for your particular use case:

```
def compute_func(a, b, c):
        ...  # long computation
        return result  

compute_func = mem.cache(compute_func)

class Foo(object):
    def __init__(self, args):
        self.data = None

    def compute(self, ...):
        ...
        self.data = compute_func(self.a, self.b, 40)
```

This way you are caching a pure function and passing explicitly the arguments from self you need, so that joblib will recompute only if those arguments changed and not any other attributes not relevant in self.

I am going to close this one, feel free to reopen if you feel you have been misunderstood @smidm.

**Closed** 2016-11-29 17:15 UTC

**Comment by smidm** [comment] 2016-11-30 07:07
That makes sense. Thanks for feedback.

**Comment by lesteve** [comment] 2016-11-30 10:01
Nice suggestion from @ogrisel in the particular case where you know that the result `compute` method does not depend on `self`: use `self.method = mem.cache(self.method, ignore='self')`. The problem is this that it is very fragile from a maintenance point of view, i.e. it is very easy to forget about this implicit contract and break it.

**Comment by lesteve** [comment] 2016-11-30 10:07
I opened a PR #432 to improve the doc about caching methods.
