### ISSUE TITLE
Caching within parallel processing not working in Jupyter

### ISSUE THREAD

**Issue by dsevero** [joblib/joblib#1069] opened 2020-06-17 04:48 UTC
`Memory` and `Parallel` work fine independently in Jupyter, but once combined they do not. The simplest way to reproduce this is with the example given at: https://joblib.readthedocs.io/en/latest/auto_examples/nested_parallel_memory.html#sphx-glr-download-auto-examples-nested-parallel-memory-py

Running the `.py` works fine both in python and ipython, but the `.ipynb` running in Jupyter does not. This can be seen by noticing that the second round (that should take advantage of caching) takes the same time as the first round. Also, the following is printed multiple times:

```
JobLibCollisionWarning: Cannot detect name collisions for function 'costly_compute'
```

**Comment by lesteve** [comment] 2020-06-17 08:48
Duplicate of #1035 closing.

**Closed by lesteve** 2020-06-17 08:48 UTC
