### ISSUE TITLE
With large number of short jobs joblib fails with CancelledError

### ISSUE THREAD

**Issue by hugorichard** [joblib/joblib#957] opened 2019-11-05 16:59 UTC
If I run this code

```python
    import time
    from joblib import Parallel, delayed, load
    from dask_jobqueue import SLURMCluster
    from dask.distributed import Client
    from joblib import parallel_backend
    cluster = SLURMCluster(diagnostics_port=1243)
    cluster.scale(4)
    client = Client(cluster)  # registers as the default "dask" backend 
    parallel_backend('dask')
    time.sleep(10)  # wait for the cluster to be up and running
    print("cluster setup")


    def do_launch_classification():
        def do_launch_classification_study():
            time.sleep(0.1)

        Parallel(n_jobs=-1,
             verbose=1000)(delayed(do_launch_classification_study)()
                           for study_path in range(34)
                           for model, name in enumerate(range(24))
                           for i_split, split in enumerate(range(5)))
    do_launch_classification()
```

I get this error

```python-traceback
distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x7fc813d945f0> of <Future: status: cancelled, type: list, key: do_launch_classification_study-batch-234b27edb1e0493f90035dc2c1de8c61>:
Traceback (most recent call last):
  File "/scratch/hrichard/venvs/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 287, in execute_callback
    fn(fut)
  File "/home/parietal/hrichard/joblib/joblib/_dask.py", line 260, in callback_wrapper
    result = future.result()
  File "/scratch/hrichard/venvs/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 224, in result
    raise result
concurrent.futures._base.CancelledError: do_launch_classification_study-batch-234b27edb1e0493f90035dc2c1de8c61
```

My jobqueue.yaml:

```yaml
    jobqueue:

        slurm:

            name: dask-worker

            cores: 40

            memory: 250GB

            processes: 2

            local-directory: /scratch/hrichard/dask 

            log-directory: /scratch/hrichard/dask/log 

            death-timeout: 30
```

Interestingly if I set time.sleep(1) instead of time.sleep(0.1) everything works fine.

**Comment by lesteve** [comment] 2020-01-08 09:45
It would be nice to:
- retry with the latest version of dask and distributed
- if the issue is still here, try to reproduce with `dask.distributed.LocalCluster`. I would (wildy-)guess that this is a problem with distributed rather than dask-jobqueue but I may be wrong ...

**Comment by pierreglaser** [comment] 2020-04-03 13:20
Thanks for the report @hugorichard.
I can reproduce locally using a `LocalCluster`:
```python
import time

from dask.distributed import Client
from joblib import Parallel, delayed, parallel_backend


if __name__ == "__main__":
    client = Client()

    with parallel_backend(backend="dask", n_jobs=2):
        Parallel(verbose=1000)(delayed(time.sleep)(1e-5) for _ in range(100))
```

Will investigate and write a follow up.

**Comment by pierreglaser** [comment] 2020-05-01 14:27
Just to get to the bottom of this: I think what we're seeing is a race condition happening during the executions of the last joblib callbacks during the manipulation of `future` results. At least in my reproducer, I believe the `backend` of the `Parallel` objects, holding references to `futures` is garbage collected before the last `joblib` `callbacks` are executed. I imagine that at `future` collection, the result of the future available in the `workers` gets dismissed, and thus `future.result()` (which is a call happening in `callback_wrapper`) raises a `CancelledError`.

IMO it is not as bad as I thought it was, because this is "simply" a race condition happening during garbage collection, and not a `dask` issue happening in the midst of the `Parallel.__call__`: you still obtain results from your `Parallel` call, although you get noisy errors from `distributed`. 

***

I now understand why #1025 fixes this: (`dask`) `future.result` is now only called once for each result in a dedicated `_callback` and the said situation cannot happen anymore.

cc @ogrisel if you wanted a proper explanation.

**Comment by hugorichard** [comment] 2020-05-01 16:37
Thanks for this Pierre !

**Comment by lesteve** [comment] 2020-05-13 04:18
#1025 has been merged, so closing this one.

**Closed by lesteve** 2020-05-13 04:18 UTC
Labels: bug, dask backend, high priority
