### ISSUE TITLE
Memory Leak in joblib.Parallel

### ISSUE THREAD

**Issue by umbernhard** [joblib/joblib#721] opened 2018-07-20 18:13 UTC
Apologies if this issue has been flagged before, I didn't see anything about it though. I've been running the following bit of code: 

```
def compute(margin, N_wl, pi, alpha, n): #start, end):

    ret_val = 0
    #for n in range(start, end):
    p1 = 0.5 + margin/2
    q_alpha = hypergeom.ppf(1-alpha, N_wl, N_wl/2, n) # upper alpha quantile of null distribution
    prob_select_N = binom.pmf(n, N_wl, pi) # probability of selecting n out of N_wl at sampling rate pi
    pvalue_nw = hypergeom.sf(q_alpha, N_wl, N_wl*p1, n) # probability of alternative distr falling above q_alpha
    return prob_select_N*pvalue_nw

def compute_unconditional_power(margin, N_wl, pi, alpha):
    '''
    Compute unconditional power of the test.

    margin = vote margin (votes for w / votes for w or l) in the population
    N_wl = the total number of ballots for either the winner or loser in the population,
    pop = total population size,
    pi = the sampling probability,
    alpha = the type I error rate
    '''
    unlikely_draw_lower = binom.ppf(0.005, N_wl, pi)
    unlikely_draw_upper = binom.ppf(0.995, N_wl, pi)
    power_sum = 0

    powers = Parallel(n_jobs=num_cores)(delayed(compute)(margin, N_wl, pi, alpha, n) \
            for n in range(int(unlikely_draw_lower), int(unlikely_draw_upper)))

    return sum(powers)
```

And i've noticed two things: the way that the parallel processes get spun up in 0.12.1 is different than in 0.11, and that this code, which works fine in 0.11, results in a memory leak in 0.12.1. Typically I get the following error, which as far as I can tell is just joblib's way of handling an OOM: 

``` 
/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/process_executor.py:634:  UserWarning: A worker timeout while some jobs were given to the executor. You might want to use a longer timeout for the executor. 
  "the executor.", UserWarning
Traceback (most recent call last):
  File "gen_plot_data.py", line 214, in <module>
    main()
  File "gen_plot_data.py", line 165, in main
    bbp_ss = get_bbp_sample_size(prop_winner, Ntot, alpha)
  File "gen_plot_data.py", line 115, in get_bbp_sample_size
    quants[quant] = get_sample_for_power(margin, Ntot, alpha, quant/100.0, 1/float(Ntot))
  File "gen_plot_data.py", line 106, in get_sample_for_power
    x = compute_unconditional_power(margin, Ntot, pi, alpha)
  File "gen_plot_data.py", line 93, in compute_unconditional_power
    for n in range(int(unlikely_draw_lower), int(unlikely_draw_upper)))
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 962, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 865, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python2.7/dist-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.```

**Comment by fednem** [comment] 2018-07-23 09:55
I am having the exact same issue: code that worked fine with joblib 0.11 throw the BrokenProcessPool error after the upgrade to 0.12.1.

**Comment by ogrisel** [comment] 2018-07-23 11:50
Could you please provide is a minimal reproduction example that does not depend on external code?
https://matthewrocklin.com/blog//work/2018/02/28/minimal-bug-reports

Also: if you get a BrokenProcessPool, the program should terminate. How can you observe a memory leak in this case?

If you run the same code sequentially (using n_jobs=1 or using a Python for loop instead of a Parallel loop) do you observe a memory leak?

**Comment by ogrisel** [comment] 2018-07-23 11:52
@fednem it would be great if you could open a new issue with your own minimal reproduction case for the `BrokenProcessPool` exception you get.

The joblib test suite pass, so it's not possible for us to debug without a way to reproduce the problem.

**Comment by ogrisel** [comment] 2018-07-23 12:23
I can reproduce the leak with the following script:

```python
from joblib import Parallel, delayed
from scipy.stats import hypergeom, binom
import psutil
import time


num_cores = 10


def print_mem(p):
    rss = p.memory_info().rss
    print(f"[{p.pid}] memory usage: {rss / 1e6:0.3} MB")


def print_all_mem():
    p = psutil.Process()
    procs = [p] + p.children(recursive=True)
    for p in procs:
        print_mem(p)

def compute(margin, N_wl, pi, alpha, n):
    ret_val = 0
    #for n in range(start, end):
    p1 = 0.5 + margin/2
    q_alpha = hypergeom.ppf(1-alpha, N_wl, N_wl/2, n) # upper alpha quantile of null distribution
    prob_select_N = binom.pmf(n, N_wl, pi) # probability of selecting n out of N_wl at sampling rate pi
    pvalue_nw = hypergeom.sf(q_alpha, N_wl, N_wl*p1, n) # probability of alternative distr falling above q_alpha
    return prob_select_N*pvalue_nw


def compute_unconditional_power(margin, N_wl, pi, alpha):
    '''
    Compute unconditional power of the test.

    margin = vote margin (votes for w / votes for w or l) in the population
    N_wl = the total number of ballots for either the winner or loser in the population,
    pop = total population size,
    pi = the sampling probability,
    alpha = the type I error rate
    '''
    unlikely_draw_lower = binom.ppf(0.005, N_wl, pi)
    unlikely_draw_upper = binom.ppf(0.995, N_wl, pi)
    power_sum = 0

    powers = Parallel(n_jobs=num_cores)(delayed(compute)(margin, N_wl, pi, alpha, n) \
            for n in range(int(unlikely_draw_lower), int(unlikely_draw_upper)))

    return sum(powers)


for i in range(1000):
    if i % 100 == 0:
        print(f"# Iteration {i}:")
        print_all_mem()
    compute_unconditional_power(1, 1000, 0.5, 0.1)
```

Here is the truncated output:

```
$ python joblib_leak.py 
# Iteration 0:
[16066] memory usage: 59.3 MB
# Iteration 100:
[16066] memory usage: 61.0 MB
[16079] memory usage: 34.1 MB
[16080] memory usage: 62.2 MB
[16081] memory usage: 62.0 MB
[16082] memory usage: 62.3 MB
[16083] memory usage: 62.5 MB
[16084] memory usage: 62.4 MB
[16085] memory usage: 62.4 MB
[16086] memory usage: 62.5 MB
[16087] memory usage: 62.2 MB
[16088] memory usage: 62.2 MB
[16089] memory usage: 62.4 MB
# Iteration 200:
[16066] memory usage: 61.4 MB
[16079] memory usage: 34.1 MB
[16080] memory usage: 66.6 MB
[16081] memory usage: 66.3 MB
[16082] memory usage: 66.6 MB
[16083] memory usage: 66.4 MB
[16084] memory usage: 66.4 MB
[16085] memory usage: 66.7 MB
[16086] memory usage: 66.6 MB
[16087] memory usage: 66.6 MB
[16088] memory usage: 66.3 MB
[16089] memory usage: 66.5 MB
# Iteration 300:
[16066] memory usage: 61.7 MB
[16079] memory usage: 34.1 MB
[16080] memory usage: 70.9 MB
[16081] memory usage: 70.6 MB
[16082] memory usage: 70.8 MB
[16083] memory usage: 70.7 MB
[16084] memory usage: 70.9 MB
[16085] memory usage: 70.9 MB
[16086] memory usage: 70.9 MB
[16087] memory usage: 70.6 MB
[16088] memory usage: 70.5 MB
[16089] memory usage: 70.7 MB
...
# Iteration 800:
[16066] memory usage: 62.2 MB
[16079] memory usage: 34.1 MB
[16080] memory usage: 92.4 MB
[16081] memory usage: 91.8 MB
[16082] memory usage: 91.3 MB
[16083] memory usage: 91.1 MB
[16084] memory usage: 91.7 MB
[16085] memory usage: 92.1 MB
[16086] memory usage: 91.5 MB
[16087] memory usage: 91.4 MB
[16088] memory usage: 91.8 MB
[16089] memory usage: 91.0 MB
# Iteration 900:
[16066] memory usage: 62.2 MB
[16079] memory usage: 34.1 MB
[16080] memory usage: 96.5 MB
[16081] memory usage: 96.3 MB
[16082] memory usage: 95.6 MB
[16083] memory usage: 95.2 MB
[16084] memory usage: 95.9 MB
[16085] memory usage: 96.4 MB
[16086] memory usage: 95.9 MB
[16087] memory usage: 95.5 MB
[16088] memory usage: 96.2 MB
[16089] memory usage: 95.3 MB

```

**Comment by ogrisel** [comment] 2018-07-23 12:24
The sequential code does not seem to have the leak and adding a call to `gc.collect()` inside the inner function does not seem to fix the issue. Will have to try to make it minimal to investigate.

**Comment by jramapuram** [comment] 2018-08-09 22:43
Using joblib w/loki for a ML pipeline and I see this happening slowly. Is this resolved in your fork @ogrisel  ?

**Comment by ogrisel** [comment] 2018-08-21 09:49
joblib 0.12.2 now restarts workers when it detects a memory leak. @umbernhard @jramapuram can you please try on your workload with joblib 0.12.2 to check that this fixes the problem?

**Comment by ogrisel** [comment] 2018-08-27 12:52
I forgot to say: the memory leak protection requires installing the psutil module as an optional dependency. Can you please try and report back?

**Comment by jramapuram** [comment] 2018-08-27 12:54
@ogrisel : I use anaconda3; it already has psutil

**Comment by GaelVaroquaux** [comment] 2018-08-30 07:41
Should we add a gc.collect in joblib, before sending the results back?

**Comment by ogrisel** [comment] 2018-08-30 12:07
This is already done since joblib 0.12.2 when psutil is available. This is not done systematically since it can be very expensive.

https://github.com/joblib/joblib/blob/master/joblib/externals/loky/process_executor.py#L436-L463

**Comment by ogrisel** [comment] 2018-09-05 08:59
We have improve this further in loky 2.3.0 (now merged in joblib master) so as to issue a gc.collect() from time to time even when psutil is not available.

**Comment by H0bbitBaron** [comment] 2018-09-06 08:45
Hi, @ogrisel ! Does this can fix https://github.com/joblib/joblib/issues/167?

**Comment by ogrisel** [comment] 2018-09-09 17:04
I cannot reproduce the issue reported in #167 (even with old versions of joblib such as 0.8.4).

**Comment by ogrisel** [comment] 2018-09-09 17:06
@pierreglaser you did some tests last week. Can you confirm that the bug reported in this issue (#721) is fixed in joblib 0.12.4? Was this a bug only in Python 2.7 that was already fixed in Python 3.6+?

**Comment by pierreglaser** [comment] 2018-09-10 10:18
Here is an update on this issue.

@jramapuram I tried to recreate the memory leak using your script, joblib 0.12.4 and with no psutil with 
- python 2.7.14
- python 3.7.0

I first generated images:
```python
import numpy as np
from PIL import Image

N_IMAGES = 100

for i in range(N_IMAGES):
    imarray = np.random.rand(1000, 1000, 3) * 255
    im = Image.fromarray(imarray.astype('uint8')).convert('RGBA')
    im.save('assets/tests_png/result_image_{}.png'.format(i))
```

ran your script 
```python
import os
import sys
import pdb
import time
import numpy as np
import joblib
from joblib import Parallel, delayed
from PIL import Image
import pandas as pd

BATCH_SIZE = 99
N_JOBS = 2
NUM_TRIALS = 50

NO_PSUTIL = False
try:
    import psutil
    print('using psutil')
except Exception:
    NO_PSUTIL = True
    print('not using psutil')


def print_mem(p):
    rss = p.memory_info().rss
    print("[{}] memory usage: {} MB".format(p.pid, rss / 1e6))
    return rss


def print_all_mem(no_psutil=False):
    if no_psutil:
        stdout = os.popen('pgrep -f loky| xargs -I"{}" ps -p {} -o pid,rss')
        stdout = stdout.read()
        lines_mems = stdout.split('\n')
        mems = {}
        for line in lines_mems[1::2]:
            print(line)
            pid, mem = line.split('  ')
            mems[pid] = int(mem)
        return mems

    else:
        p = psutil.Process()
        procs = [p] + p.children(recursive=True)
        mems = {}
        for p in procs:
            mems[p] = print_mem(p)
        return mems


class CropLambda(object):
    """A class to do a crop of an image to a region.

    Args:
        window_size: the resized return image [not related to img_percentage].
        max_img_percentage: the maximum percentage of the image to use for the crop.
    """

    def __init__(self, path, window_size, max_img_percentage=0.15):
        self.path = path
        self.window_size = window_size
        self.max_img_percent = max_img_percentage

    def scale(self, val, newmin, newmax):
        return (((val) * (newmax - newmin)) / (1.0)) + newmin

    def __call__(self, crop):
        ''' converts [crop_center, x, y] to a 4-tuple
            defining the left, upper, right, and lower
            pixel coordinate and return a lambda '''
        with open(self.path, 'rb') as f:
            with Image.open(f) as img:
                img_size = np.array(img.size)  # numpy-ize the img size (tuple)

                # scale the (x, y) co-ordinates to the size of the image
                assert crop[1] >= 0 and crop[1] <= 1, "x needs to be \in [0, 1]"
                assert crop[2] >= 0 and crop[2] <= 1, "y needs to be \in [0, 1]"
                x, y = [
                    int(self.scale(crop[1], 0, img_size[0])),
                    int(self.scale(crop[2], 0, img_size[1]))
                ]

                # calculate the scale of the true crop using the provided scale
                # Note: this is different from the return size, i.e. window_size
                crop_scale = min(crop[0], self.max_img_percent)
                crop_size = np.floor(img_size * crop_scale).astype(int) - 1

                # bound the (x, t) co-ordinates to be plausible
                # i.e < img_size - crop_size
                max_coords = img_size - crop_size
                x, y = min(x, max_coords[0]), min(y, max_coords[1])

                # crop the actual image and then upsample it to window_size
                # resample = 2 is a BILINEAR transform, avoid importing PIL for enum
                # TODO: maybe also try 1 = ANTIALIAS = LANCZOS
                crop_img = img.crop((x, y, x + crop_size[0], y + crop_size[1]))
                # pdb.set_trace()
                return crop_img.resize(
                    (self.window_size, self.window_size), resample=2
                )


class CropLambdaPool(object):
    def __init__(self, num_workers):
        self.num_workers = num_workers
        self.backend = 'loky'

    def _apply(self, lbda, z_i):
        return lbda(z_i)

    def __call__(self, list_of_lambdas, z_vec):
        # pdb.set_trace()
        res = Parallel(
            n_jobs=self.num_workers, backend=self.backend
        )(
            delayed(self._apply)(list_of_lambdas[i], z_vec[i])
            for i in range(len(list_of_lambdas))
        )
        return res


def python_crop_bench(paths, scale, x, y, window_size, max_img_percentage):
    crop_lbdas = [CropLambda(p, window_size, max_img_percentage) for p in paths]

    # pdb.set_trace()
    z = np.hstack(
        [np.expand_dims(scale, 1),
         np.expand_dims(x, 1),
         np.expand_dims(y, 1)]
    )
    return CropLambdaPool(num_workers=N_JOBS)(crop_lbdas, z)


if __name__ == "__main__":
    python_time = []
    path_list = [
        './assets/tests_png/result_image_{}.png'.format(i)
        for i in range(1, BATCH_SIZE + 1)
    ]
    x, y, scale = [0.1] * BATCH_SIZE, [0.1] * BATCH_SIZE, [0.9] * BATCH_SIZE
    memory_use = {}
    for i in range(1, NUM_TRIALS + 1):
        if i % 2 == 0:
            print('iteration no. {}'.format(i))
            mem_use = print_all_mem(no_psutil=NO_PSUTIL)
            memory_use[i] = mem_use
        start_time = time.time()
        crops = python_crop_bench(path_list, scale, x, y, 32, 0.25)
        python_time.append(time.time() - start_time)

    print(
        "python crop average over {} trials : {} +/- {} sec".format(
            NUM_TRIALS, np.mean(python_time), np.std(python_time)
        )
    )
    memory_use_path = 'memory_use_py{}_joblib_{}.csv'.format(
        sys.version[0], joblib.__version__.replace('.', '')
    )
    memory_use = pd.DataFrame(memory_use).T
    memory_use.index.name = 'iter_number'
    memory_use.columns.name = 'PID'
    memory_use.to_csv(memory_use_path)
```
and profiled the memory

Here is the increase in memory in KBs for the parent processes and the child processes
![memory_increase](https://user-images.githubusercontent.com/18555600/45291491-a352d480-b4f2-11e8-967e-60abe771c0a2.png)

Altough there is a slight increase (~350KB), it seems reasonable compared to each image size (~3MB), given that 100 images are processed 50 times. 

@ogrisel  waiting for your opinion on this. I can try longer tests if you think this is necessary. (tests right now are taking approx 5min on my machine)

Requirements for each environment:

python3 virtual environment
```txt
cycler==0.10.0
joblib==0.12.4
kiwisolver==1.0.1
matplotlib==2.2.3
numpy==1.15.1
pandas==0.23.4
Pillow==5.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
scipy==1.1.0
six==1.11.0
```
python2 virtual environment
```txt
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
decorator==4.3.0
enum34==1.1.6
ipython==5.8.0
ipython-genutils==0.2.0
joblib==0.12.4
numpy==1.15.1
pandas==0.23.4
pathlib2==2.3.2
pexpect==4.6.0
pickleshare==0.7.4
PIL==1.1.7
Pillow==5.2.0
prompt-toolkit==1.0.15
ptyprocess==0.6.0
Pygments==2.2.0
python-dateutil==2.7.3
pytz==2018.5
scandir==1.9.0
scipy==1.1.0
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
wcwidth==0.1.7
```

**Comment by jramapuram** [comment] 2018-09-11 11:39
Hi @pierreglaser ,

Thanks for taking the time to go over this in detail,I appreciate it! One problem is that real life scenarios use ~1 million images which are iterated over ~200-2000 times (so 1M * 2000).  In such scenarios the  problem gets exasperated. 

However, that being said if you believe the issue is not related to joblib (i.e. the leak is in say PIL) then I can look into reproducing this for them there.

In either case I would expect a fixed increase in memory (which  is totally acceptable), but a leak is probably not sustainable in large scale projects that use joblib.

**Comment by tomMoral** [comment] 2018-09-11 12:30
@jramapuram another possible reason you run out of memory with `joblib` is the memmapping of the input/output. The memmapping is typically done in `/dev/shm` which is in memory and this part of the memory is freed only at the end of a `Parallel` call (or in the case of a managed `Parallel`, when `__exit__` is called).

So your issue might be that you run out of memory because your call to `Parallel` processes too many images at once. Note that this cannot be seen by measuring the process size as the shared memory is not included. If this is the case, your first call to `Parallel` with the full batch of image should fail and it should also have been failing with `joblib0.11`. Is that the case or do you see the memory increase with each call to `Parallel`?

**Comment by jramapuram** [comment] 2018-09-11 13:17
@tomMoral : good question; I see the memory increasing over time. Generally at each epoch the model processes all of the data: eg the 1M * 2000 images. On the next epoch the model processes the same images again. If it were a fixed increase would this increase epoch-to-epoch? 

I can check using `joblib <0.11` : but I think that works fine. I initially used vanilla multiprocessing (which I'm guessing is what `<0.11` uses? I can re-check, but I'm pretty sure there was no issue there leading me to believe the issue is in `loky`

**Comment by ogrisel** [comment] 2018-09-13 12:26
Also with psutil, the worker should be restarted if they leak too much memory.

**Comment by ogrisel** [comment] 2018-09-13 12:27
I also agree that a *minimal* reproducing example would really help.

**Comment by jramapuram** [comment] 2018-09-13 12:44
I agree w.r.t. the minimal example, however I will not have time for the
next 60 days or so to get to this unfortunately.
If this is not resolved by then, I can definitely provide a simpler example.

**Comment by pierreglaser** [comment] 2018-09-14 09:13
Update on this:
I used a bigger machine, and ran the same script, but generating 500 images
The parameters were
```python
BATCH_SIZE = 500
NUM_TRIALS=500
N_JOBS=4
```
![image](https://user-images.githubusercontent.com/18555600/45541310-0f914900-b80f-11e8-8c11-99acc57cc89c.png)

**Comment by ogrisel** [comment] 2018-09-14 10:26
Thanks @pierreglaser . What is the total run time for this experiment?

This step increase to 800 kB and then to 1500 kB on python 3 are weird. I think we need to run this on a machine (just on a few workers, e.g. 2 or 4) but for a longer time (e.g. a couple of hours).

**Comment by pierreglaser** [comment] 2018-09-14 10:32
the scripts ouptut an average time of 5 sec per experiments per trial, times 500 trials, so around 2500 seconds ---> 40 minutes. 
I wil run this for 3000 trials and see.

**Comment by ogrisel** [comment] 2018-09-19 08:28
This looks stable enough for me. Maybe the slow increase is caused by the python VM itself that fragments its memory when allocating and deallocating many objects over time?

Anyway I think this is fine and the the original problem reported in this issue has definitely be fixed by the regular call to gc.collect in the workers.

**Closed by ogrisel** 2018-09-19 08:28 UTC

**Comment by jramapuram** [comment] 2018-09-19 08:29
Thank! If I have any further issues I will report back.

**Comment by YubinXie** [comment] 2019-06-03 17:06
I am having the following issues but the script was able to finish working (I have 10 workers).

```
/Users/xiey/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/Users/xiey/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/Users/xiey/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/Users/xiey/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
```

Does this information mean the calculation in my code is wrong? I am not sure if I can believe the results...
