### ISSUE TITLE
memory bloating after 100000+ iteration?

### ISSUE THREAD

**Issue by varoudis** [joblib/joblib#682] opened 2018-05-18 11:48 UTC
Running the same operations for upwards of 100000-130000 times (This takes a day or two) the memory usage starts increasing from 10GB (very steady until then) to 100+Gb until RAM and SWAP is full.

```
out = np.memmap('outdata.mmap', dtype=np.int32, shape=(const_data_len, 100), mode='w+')

num_cores = 24
num_pre_workers = 40 

Parallel(n_jobs=num_cores, pre_dispatch=num_pre_workers, verbose=1, max_nbytes=None)(delayed(runparallel)(const_data, r, out) for r in range(const_data_len))

```
parallel call writes only on memmap and everything local to runparallel is deleted (del) before return.

Any known issues with running tasking a bigger than a certain number?

**Comment by GaelVaroquaux** [comment] 2018-05-18 20:51
1. If you put n_jobs=1, does the problem disappear?

2. If not, can you provide an example that we can run to reproduce.

**Comment by varoudis** [comment] 2018-05-20 07:54
Ill try to make some example code as n_jobs=1 will take a month at least :)

**Comment by tomMoral** [comment] 2018-05-20 08:41
You can maybe try to make an example with just the io. Remove the computations inside `runparallel`.

Looking at your example, it seems to me  that you return the out array in `runparallel`. This would duplicate it, causing the size of the out buffer holding the result to explode.

**Comment by tomMoral** [comment] 2018-05-20 16:05
I cannot reproduce your bug with this script. So I do not think there is an issue with the number of iterations.

```python
import numpy as np
from joblib import  Parallel, delayed


def ret(out, i):
    out[i, :] = 1


if __name__ == "__main__":
    N, K = 100000, 100
    out = np.memmap('outdata.mmap', dtype=np.int32, shape=(N, K), mode='w+')
    out[:, :] = 0
    c = Parallel(n_jobs=6, pre_dispatch=20, verbose=1, max_nbytes=None)(delayed(ret)(out, i) for i in range(N))
    assert np.all(out == 1)

```

In this case, memory profiling do not show any increases in memory for `N=100000` and `1000000`:
![image](https://user-images.githubusercontent.com/3321081/40280678-5cbbc426-5c57-11e8-98d9-33cae8069575.png)

But I don't know how close I am from the use case you have. Am I missing a key point with your usage?

**Comment by varoudis** [comment] 2018-05-21 09:36
Let me rule out a couple of other things and make a simple example and Ill report back.
Any good memory profiling libs or tools in python that you use?

**Comment by tomMoral** [comment] 2018-08-14 09:30
The recent release `0.12.2` include `loky 2.2.0`, which provides safeguards against memory leaks. I think this should solve your issue here as the workers seeing an increased memory usage are periodically killed and replace by fresh workers.

I am closing this one but feel free to re-open it if you still see this happening with the newest version of `joblib`.

**Closed by tomMoral** 2018-08-14 09:30 UTC
