### ISSUE TITLE
BUG: parallel crashes when array too big.

### ISSUE THREAD

**Issue by kingjr** [joblib/joblib#344] opened 2016-04-30 14:38 UTC
I am not sure whether this is a bug or a bad parametrization on my part, but I get an error when passing a *unique* large arrays to `Parallel` with `max_nbytes=None`, and `n_jobs > 1`.

```
from joblib import Parallel, delayed
import numpy as np

def func(X):
    pass

X = np.random.rand(841, 306, 1445)
chunks = map(list, zip(*[np.array_split(X, 1)]))  # note n_jobs > n_splits

parallel = Parallel(-1, max_nbytes=None)
p_func = delayed(func)

out = parallel(p_func(chunk) for chunk in chunks)
```

However, it works is `max_nbytes` isn't provided, or when the array is smaller.

This [issue](https://github.com/mne-tools/mne-python/issues/3190) is replicable on ubuntu 14.04 + anaconda build with joblib `0.9.4` and numpy `1.11.0`

It may be related to https://github.com/joblib/joblib/issues/138

**Comment by lesteve** [comment] 2016-05-03 14:19
I can reproduce the problem. It looks like a multiprocessing limitation AFAICT but I haven't had time to put together a snippet giving the same error without joblib.

For reference, here is the full stacktrace I get (with Python 3):

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/tmp/test_joblib.py in <module>()
     11 p_func = delayed(func)
     12 
---> 13 out = parallel(p_func(chunk) for chunk in chunks)

/home/lesteve/dev/joblib/joblib/parallel.py in __call__(self, iterable)
    745                 # consumption.
    746                 self._iterating = False
--> 747             self.retrieve()
    748             # Make sure that we get a last message telling us we are done
    749             elapsed_time = time.time() - self._start_time

/home/lesteve/dev/joblib/joblib/parallel.py in retrieve(self)
    666                 job = self._jobs.pop(0)
    667             try:
--> 668                 self._output.extend(job.get())
    669             except tuple(self.exceptions) as exception:
    670                 # Stop dispatching any new job in the async callback thread

/home/lesteve/miniconda3/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

/home/lesteve/miniconda3/lib/python3.5/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    383                         break
    384                     try:
--> 385                         put(task)
    386                     except Exception as e:
    387                         job, ind = task[:2]

/home/lesteve/dev/joblib/joblib/pool.py in send(obj)
    369                 buffer = BytesIO()
    370                 CustomizablePickler(buffer, self._reducers).dump(obj)
--> 371                 self._writer.send_bytes(buffer.getvalue())
    372             self._send = send
    373         else:

/home/lesteve/miniconda3/lib/python3.5/multiprocessing/connection.py in send_bytes(self, buf, offset, size)
    198         elif offset + size > n:
    199             raise ValueError("buffer length < offset + size")
--> 200         self._send_bytes(m[offset:offset + size])
    201 
    202     def send(self, obj):

/home/lesteve/miniconda3/lib/python3.5/multiprocessing/connection.py in _send_bytes(self, buf)
    391         n = len(buf)
    392         # For wire compatibility with 3.2 and lower
--> 393         header = struct.pack("!i", n)
    394         if n > 16384:
    395             # The payload is large so Nagle's algorithm won't be triggered

error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by lesteve** [comment] 2016-06-20 08:38
@kingjr out of interest is there a particular reason why you wanted to disable memmaping by setting mmap_mode=None?

**Comment by kingjr** [comment] 2016-06-20 08:50
You mean `max_nbytes` ? It was set by the default in the [package](https://github.com/mne-tools/mne-python/blob/master/mne/parallel.py) I was using. 

(`mmap_mode` isn't documented BTW)

**Comment by lesteve** [comment] 2016-06-20 09:19
> You mean max_nbytes ? It was set by the default in the package I was using. 

I am not following the entire logic but I would hope that MNE-Python doesn't set it to None by default. Quickly looking at the code it depends on some configuration, maybe you can try to tweak yours.

> (mmap_mode isn't documented BTW)

Funny you are saying this, I just pushed a commit to fix it.

Also I can reproduce the problem without any joblib (runs this snippet at your own risks, it did freeze my computer for a few minutes).

```py
import multiprocessing

pool = multiprocessing.Pool(2)
def f(x):
    return x.size
import numpy as np
a = np.ones((841, 306, 1445))
pool.apply(f, [a])
```

so I am guessing this is a limitation of multiprocessing when the pickled input arguments are too big. The underlying cause is that you can not send more that 2**31 bytes through the socket.

**Comment by kingjr** [comment] 2016-06-20 09:23
> I am not following the entire logic but I would hope that MNE-Python doesn't set it to None by default. 

I'm not sure, but I'll try to have a look.

> so I am guessing this is a limitation of multiprocessing when the pickled input arguments are too big. The underlying cause is that you can not send more that 2**31 bytes through the socket.

So this is bleeding edge from pickle? Shall we add an explicit error when more than 2**31 bytes are sent through the socket?

**Comment by lesteve** [comment] 2016-06-20 09:36
> So this is bleeding edge from pickle? Shall we add an explicit error when more than 2**31 bytes are sent through the socket?

It's not pickle but multiprocessing. You can have a look at https://bugs.python.org/issue17560 for more details. I think this pretty much sums it up:
> But I can't help feeling that multigigabyte arrays should be transferred using shared mmaps rather than serialization.

**Comment by lesteve** [comment] 2016-06-20 09:40
Just for clarity's sake, what I meant in my previous message, you should be using memmapping in your case and I think the thing to investigate is why `mmap_mode` is set to None and thus memmapping disabled. I find it slightly hard to believe that this is the default behaviour from MNE-Python.

**Comment by kingjr** [comment] 2016-07-08 14:38
@agramfort a quick look wasn't sufficient for me to understand the default `mmap_mode` of MNE-Python, if you have time to give a glance.

**Comment by agramfort** [comment] 2016-07-09 17:25
@kingjr did you use mne.set_cache_dir ?

I read in the code:

joblib supports memapping pool but "MNE_CACHE_DIR" '
                        'is not set in MNE-Python config. To enable it, use, '
                        'e.g., mne.set_cache_dir(\'/tmp/shm\'). This will '
                        'store temporary files under /dev/shm and can result '
                        'in large memory savings.

**Comment by kingjr** [comment] 2016-07-09 21:30
> @kingjr did you use mne.set_cache_dir ?

@agramfort no I haven't, but the default may have been screwed by an attempted cuda install

**Comment by agramfort** [comment] 2016-07-10 11:42
can you provide a testing script using mne.parallel to replicate the pb?

**Comment by kingjr** [comment] 2016-07-10 12:41
@agramfort see https://github.com/mne-tools/mne-python/issues/3190

**Comment by ogrisel** [comment] 2016-07-12 14:11
For the record I adapted the snippet by @lesteve to check that the issues exists both on Python 2 and Python 3 and comes from Python multiprocessing:

```
ogrisel@is146148:~$ cat tmp/mp_issue17560.py 
import multiprocessing as mp

if __name__ == '__main__':
    p = mp.Pool(2)

    data = b'0' * (2 ** 31 + 1)
    print(p.apply(id, [data]))
(py35)ogrisel@is146148:~$ workon py35
(py35)ogrisel@is146148:~$ python tmp/mp_issue17560.py
Traceback (most recent call last):
  File "tmp/mp_issue17560.py", line 8, in <module>
    print(p.apply(id, [data]))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 253, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
(py35)ogrisel@is146148:~$ workon py27
(py27)ogrisel@is146148:~$ python tmp/mp_issue17560.py
Traceback (most recent call last):
  File "tmp/mp_issue17560.py", line 8, in <module>
    print(p.apply(id, [data]))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 244, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
SystemError: NULL result without error in PyObject_Call
```

You get different error messages but it crashes in both cases. So the only solution I see is to keep using the memmaping feature of joblib (which is enabled by default with `max_nbytes='1M'`).

Alternatively it's possible to use the `backend='threading'` option if you know that the workload is not GIL-bound (e.g. CPU intenstive Cython or numpy / scipy function calls that release the GIL). Trusting MKL or OpenBLAS to handle parallelism by themselves and leaving `n_jobs=1` is another option when you know that the CPU intensive workload is all in BLAS calls, typically matrix / matrix multiplications.

Closing this.

**Closed by ogrisel** 2016-07-12 14:11 UTC

**Comment by kingjr** [comment] 2016-07-12 14:12
ok thanks @lesteve & @ogrisel
