### ISSUE TITLE
Error in raising exception

### ISSUE THREAD

**Issue by TurnaevEvgeny** [joblib/joblib#267] opened 2015-11-02 20:06 UTC
This looks like a bug to me.

<pre><code>
    rl = Parallel(n_jobs=num_cores, verbose=100)(delayed(FetchAPNs)(f, db_host, db_user, db_name, db_password, bg_limit) for f in fips_list)
  File "/Users/eturnaev/venv/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "/Users/eturnaev/venv/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 4 arguments (2 given)
</code></pre>

Exception class: `<class 'joblib.my_exceptions.JoblibOperationalError'>`

Original exception printed with traceback.print_exc()
<pre><code>
Traceback (most recent call last):
  File "/Users/eturnaev/venv/lib/python2.7/site-packages/joblib/parallel.py", line 731, in retrieve
    self._output.extend(job.get())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
TransportableException: <unprintable TransportableException object>
</code></pre>

joblib==0.9.3

**Comment by GaelVaroquaux** [comment] 2015-11-02 20:14
Is this a duplicate of #261 ?

**Comment by lesteve** [comment] 2015-11-02 22:22
> Is this a duplicate of #261 ?

Very likely.

**Closed** 2015-11-04 09:33 UTC
