### ISSUE TITLE
Silent recalculation of result when trying to cache a lambda with dill

### ISSUE THREAD

**Issue by bayerj** [joblib/joblib#1267] opened 2022-02-18 06:56 UTC
I have `@memory.cache`'d a function that returns a lambda expression. This is not possible to pickle, which makes joblib not cache the result and instead rerun it everytime. dill however is able to pickle such functions, and so I set it as a loky pickler. Yet, the function is still not cached and rerun everytime.

This took me quite a while to find out in two ways. First, to see that if pickling fails, joblib silences this error and does not cache. To mitigate, I use dill as a pickler but that still fails silently.

I would expect
 - joblib to crash if it cannot pickle a result, instead of silently going on,
 - joblib to crash if I explicitly set a pickler, but that is apparently not used.

I am using joblib-1.1.0, dill-0.3.4 Python 3.9.9 on Mac OS Monterey, M1. Here is what I run:

```
from joblib.memory import Memory
from joblib.externals.loky import set_loky_pickler
set_loky_pickler('dill')

memory = Memory('./cache')

@memory.cache
def do_stuff():
    return lambda: 2


x = do_stuff()
```

**Comment by bayerj** [comment] 2022-02-18 07:44
This seems related: https://github.com/joblib/joblib/issues/1046.

**Comment by GaelVaroquaux** [comment] 2022-02-18 07:55
>   • joblib to crash if it cannot pickle a result, instead of silently going on,
>   • joblib to crash if I explicitly set a pickler, but that is apparently not used.

One of the core principles of joblib is to not raise an error for code that would not raise errors without joblib.

We should raise a warning, I agree (I thought that we did).

We could add an option to turn these warnings in errors. That should probably be done in a second time.

**Comment by GaelVaroquaux** [comment] 2022-02-18 07:56
Closing as a duplicate of #1046 (where the same discussion has happened)

**Closed by GaelVaroquaux** 2022-02-18 07:56 UTC

**Comment by bayerj** [comment] 2022-02-18 07:57
> One of the core principles of joblib is to not raise an error for code that would not raise errors without joblib.
That sounds like a good idea, actually. 

But this is not a duplicate. The fact that dill apparently is not used remains.

**Comment by GaelVaroquaux** [comment] 2022-02-18 08:02
> But this is not a duplicate. The fact that dill apparently is not used remains.

Loky has nothing to do with memory: loky is for parallelism.

**Comment by bayerj** [comment] 2022-02-18 08:14
Ok, excuse my misunderstanding and thank you for your patience.

I hence take away from the conversation that there currently is no way to make joblib work with lambdas. Doing so would require quite some work in `numpy_pickle`, I suppose.

**Comment by GaelVaroquaux** [comment] 2022-02-18 08:38
> I hence take away from the conversation that there currently is no way to make joblib work with lambdas.

Not with regards to the outputs of functions in mem.cache.

> Doing so would require quite some work in numpy_pickle, I suppose.

I would agree. We would probably rather use cloud_pickle than dill,
because we really in cloud_pickle elsewhere.
