### ISSUE TITLE
Parallel failures on AppVeyor

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#558] opened 2017-10-04 09:23 UTC
While working on #556, there were some failures on Appveyor when using Loky parallel backend on very fast tasks (1000 tasks of 1ms each). See this [failing build](https://ci.appveyor.com/project/joblib-ci/joblib/build/1.0.1462/job/6920vox68gksx5f4).

There is a deadlock at some point that ends up in a timeout of pytest.

I didn't test locally on Windows.

Here is a snippet that should reproduce the problem:
```python
import time

from joblib import Parallel, delayed

backend = "loky"  # might also fail with multiprocessing
n_jobs = 2
n_inputs = 1000
task_time = 1. / n_inputs

p = Parallel(verbose=10, n_jobs=n_jobs, backend=backend)
p(delayed(time.sleep)(task_time) for i in range(n_inputs))
```

**Comment by lesteve** [comment] 2017-10-05 07:45
I tried to execute the snippet 10-15 times and I can not reproduce on my Windows VM. Also `time.sleep(0.001)` is actually sleeping for ~10ms so there is no real difference between `time.sleep(0.001)` and `time.sleep(0.002)`. Not sure whether this is the same on AppVeyor. Maybe worth trying to reproduce with a computation instead of a sleep in any case.

**Comment by ogrisel** [comment] 2017-10-06 17:00
That deadlock traceback is really fishy as there are threads loky mixed with threads from `c:\python27\lib\multiprocessing\pool.py` which is not used by loky as far as I know.

**Comment by ogrisel** [comment] 2017-10-06 17:05
The main thread is using the `multiprocessing.Pool` based backend so I think this is a deadlock in multiprocessing itself or in our usage of the multiprocessing callback API.

Loky is probably not the problem here. The thread we see in the traceback are the threads of the loky reusable process pool executor that seats in the background but should not cause the main thread to deadlock in this test.

**Comment by aabadie** [comment] 2020-07-01 13:10
Do you think this can be closed @ogrisel ?

**Comment by lesteve** [comment] 2020-07-01 13:52
Probably not relevant any more since AppVeyor is not used anymore, closing.

**Closed by lesteve** 2020-07-01 13:52 UTC
